import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text(
          'TheraWise',
          style: TextStyle(
              fontWeight: FontWeight.bold,
              fontStyle: FontStyle.italic,
              fontSize: 24,
              color: CupertinoColors.white),
        ),
        backgroundColor: Color(0xFF6200EE),
      ),
      child: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            mainAxisAlignment: MainAxisAlignment.spaceBetween,
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              Expanded(
                child: GridView.count(
                  crossAxisCount: 2,
                  crossAxisSpacing: 16,
                  mainAxisSpacing: 16,
                  children: [
                    _buildGridButton(
                      context,
                      '/log-mood',
                      CupertinoIcons.smiley_fill,
                      'Log Mood',
                      Color(0xFF4CAF50),
                    ),
                    _buildGridButton(
                      context,
                      '/cbt-exercises',
                      CupertinoIcons.bolt_fill,
                      'CBT Exercises',
                      Color(0xFF03A9F4),
                    ),
                    _buildGridButton(
                      context,
                      '/mood-tracker',
                      CupertinoIcons.chart_bar_fill,
                      'Mood Tracker',
                      Color(0xFFFFC107),
                    ),
                    _buildGridButton(
                      context,
                      '/personalized-advice',
                      CupertinoIcons.lightbulb_fill,
                      'Advice',
                      Color(0xFFFF5722),
                    ),
                  ],
                ),
              ),
              SizedBox(height: 20),
              Center(
                child: Column(
                  children: [
                    Text('Daily Tip',
                        style: TextStyle(
                            fontSize: 20,
                            fontWeight: FontWeight.bold,
                            color: CupertinoColors.black)),
                    SizedBox(height: 10),
                    Text('[Daily Tip Generated by LLM API]',
                        style: TextStyle(
                            fontSize: 16, color: CupertinoColors.systemGrey)),
                  ],
                ),
              ),
              SizedBox(height: 20),
              CupertinoButton(
                onPressed: () {
                  Navigator.pushNamed(context, '/venting-out');
                },
                color: CupertinoColors.systemRed.withOpacity(0.8),
                borderRadius: BorderRadius.circular(12),
                child: Text(
                  "Let's Vent Out",
                  style: TextStyle(
                    fontSize: 20,
                    color: Colors.white,
                    fontWeight: FontWeight.bold,
                  ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildGridButton(BuildContext context, String route, IconData icon,
      String label, Color color) {
    return GestureDetector(
      onTap: () {
        Navigator.pushNamed(context, route);
      },
      child: Container(
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(12),
          boxShadow: [
            BoxShadow(
              color: color.withOpacity(0.5),
              spreadRadius: 2,
              blurRadius: 5,
              offset: Offset(0, 3),
            ),
          ],
        ),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            Icon(icon, size: 50, color: Colors.white),
            SizedBox(height: 10),
            Text(
              label,
              style: TextStyle(
                fontSize: 18,
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
            ),
          ],
        ),
      ),
    );
  }
}
