import 'package:flutter/cupertino.dart';

class PersonalizedAdviceScreen extends StatelessWidget {
  const PersonalizedAdviceScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return CupertinoPageScaffold(
      navigationBar: CupertinoNavigationBar(
        middle: Text(
          'Personalized Advice',
          style: TextStyle(fontWeight: FontWeight.bold),
        ),
      ),
      child: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              const Text('Your Personalized Advice',
                  style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold)),
              const SizedBox(height: 10),
              const Text(
                '[Advice Generated by LLM API]',
                style: TextStyle(fontSize: 16),
              ),
              const SizedBox(height: 10),
              CupertinoButton.filled(
                onPressed: null, // Refresh Advice
                child: const Text('Get New Advice'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
